[project]
name = "psrt-ghsa-bot"
version = "0.1.0"
description = "GitHub bot for PSRT activities on GHSA"
readme = "README.md"
requires-python = ">=3.14.0"
dependencies = [
    "cvelib>=1.4.0",
    "githubkit[auth-app]>=0.13.5",
    # we might could put this into a dep group to not load it every time we install
    # inside gh actions for cron.yml or the sentry check in
    "playwright>=1.55.0",
    "pyotp>=2.9.0",
    "python-dotenv>=1.0.0",
    "sentry-sdk>=2.22.0",
]

[dependency-groups]
dev = [
    "mock>=5.2.0",
    "pytest>=8.4.2",
    "pytest-playwright>=0.7.1",
    "pytest-sugar>=1.1.1",
    "ruff>=0.14.3",
    "ty>=0.0.1a25",
]

[build-system]
requires = ["uv_build>=0.9.6,<0.10.0"]
build-backend = "uv_build"

[tool.ruff]
target-version = "py314"
src = ["src", "tests"]
line-length = 120
indent-width = 4

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D203",
    "D213",
    "COM812",
    "T201",
    "TD",  # todo without author
    "FIX002",  # Line contains TODO
    "PLR0913", # Too many arguments
    "PLR0911", # Too many returns
    "C901",   # Too complex
    "ARG001", # unused arg
    "BLE001", # blind except
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ruff.lint.per-file-ignores]
"tests/**/*.*" = [
    "A",
    "ARG",
    "B",
    "BLE",
    "C901",
    "D",
    "DTZ",
    "EM",
    "FBT",
    "G",
    "N",
    "PGH",
    "PIE",
    "PLR",
    "PLW",
    "PTH",
    "RSE",
    "S",
    "S101",
    "SIM",
    "TC",
    "TRY",
    "SLF",
    "ANN",
    "FIX",
    "TD",
    "ERA",
]
"scripts/**/*.*" = [
    "INP001",  # Implicit namespace package
    "EXE001",  # Shebang not executable
    "RUF001",  # Ambiguous unicode
    "DTZ",     # Timezone issues
    "S",       # Security issues
    "T201",    # Print statements
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.pytest.ini_options]
anyio_mode = "strict"
asyncio_default_fixture_loop_scope = "function"
