name: "PSRT GHSA Bot"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

permissions: {}

jobs:
  cron:
    runs-on: ubuntu-latest
    name: "Run PSRT Advisory Bot"
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false

      - name: Set up uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: uv sync --locked --no-editable --no-dev

      - name: Run bot
        run: uv run python src/psrt_ghsa_bot/app.py
        env:
          GH_CLIENT_ID: ${{ vars.GH_CLIENT_ID }}
          GH_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
          GH_CLIENT_PRIVATE_KEY: ${{ secrets.GH_CLIENT_PRIVATE_KEY }}
          CVE_USERNAME: ${{ vars.CVE_USERNAME }}
          CVE_API_KEY: ${{ secrets.CVE_API_KEY }}
          CVE_ENV: ${{ vars.CVE_ENV }}
