name: "PSRT GHSA Bot"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

permissions:
  contents: read

concurrency:
  group: psrt-ghsa-bot
  cancel-in-progress: false

jobs:
  cron:
    runs-on: ubuntu-latest
    name: "Run PSRT GHSA Bot"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: uv sync --locked --no-editable --no-dev

      - name: Run bot
        run: uv run python src/psrt_ghsa_bot/app.py
        env:
          GH_CLIENT_ID: ${{ vars.GH_CLIENT_ID }}
          GH_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
          GH_CLIENT_PRIVATE_KEY: ${{ secrets.GH_CLIENT_PRIVATE_KEY }}
          CVE_USERNAME: ${{ vars.CVE_USERNAME }}
          CVE_API_KEY: ${{ secrets.CVE_API_KEY }}
          CVE_ENV: ${{ vars.CVE_ENV }}
          CVE_ENABLED_REPOS: ${{ vars.CVE_ENABLED_REPOS }}
          GH_REQUIRED_ORG: ${{ vars.GH_REQUIRED_ORG }}
          SENTRY_DSN: ${{ github.event_name == 'schedule' && secrets.SENTRY_DSN || '' }}
